import { Prisma } from '@prisma/client';
import { APIError } from '../../../../shared/utils/errorHandler/APIError';
import { auditService } from '../../../../shared/utils/audit/audit.service';
import { retryableTransaction } from '../../../../shared/utils/db/withWriteConflictRetry';
import { gs1Utils } from '../../../../shared/utils/gs1/gs1.utils';
import { resolveGs1Prefix } from '../../../../shared/utils/gs1/gs1Prefix';
import { nextSsccSerial } from '../../../../shared/utils/gs1/ssccSerial';
import { reconcileLogisticUnitContent } from '../../shared/utils/reconcileLogisticUnitContent';
import {
  EPCIS_ACTION,
  EPCIS_BIZSTEP,
  EPCIS_DISPOSITION,
  EPCIS_EVENT_TYPE,
  EPCIS_RELATED_ENTITY,
} from '../../../../shared/constants/epcis.constants';
import {
  BATCH_STATUSES,
  BLOCKING_BATCH_STATUSES,
  MOVEMENT_TYPES,
  isBatchBlocked,
} from '../../constants/logistics.constants';

/**
 * `@@unique([organization_id, shipment_id])` fait déjà barrage au doublon ; sans traduction,
 * l'expéditeur reçoit un 500 illisible alors que son geste est légitime — il lui suffit de
 * choisir un autre numéro de bon.
 */
async function createShipmentOrRejectDuplicate(
  tx: Prisma.TransactionClient,
  data: Prisma.ShipmentUncheckedCreateInput
) {
  try {
    return await tx.shipment.create({ data });
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
      throw new APIError(409, {
        error: [
          {
            field: 'shipment_id',
            message: `L'expédition ${data.shipment_id} existe déjà dans cette organisation.`,
          },
        ],
      });
    }
    throw error;
  }
}

/**
 * Service pour la gestion des Expéditions (Shipments)
 */
export const shipmentService = {
  /**
   * Créer une expédition et déduire les stocks des lots associés.
   */
  async createShipment(data: {
    organization_id: string;
    id_client: string;
    shipment_id: string;
    transporteur: string;
    destination_adresse?: string;
    date_envoi: Date;
    created_by: string;
    items: Array<{ id_lot: string; quantite: number }>;
  }) {
    // Serializable + verrou optimiste (version) sur la déduction de stock : c'était le SEUL chemin
    // d'écriture en Read Committed sans garde. Une expédition qui lit un lot EN_STOCK pouvait écraser
    // un rappel posé entre-temps (le lot repartait chez le client), et deux expéditions concurrentes
    // du même lot passaient toutes les deux (sur-expédition / stock négatif). Rejoué sur conflit.
    return await retryableTransaction(async (tx) => {
      // 0.a Le client destinataire doit appartenir à l'organisation (anti-référence cross-tenant).
      // Symétrique au contrôle du fournisseur à la réception : sans cette garde, un id_client
      // d'une autre org serait accepté (et notifié lors d'un rappel).
      const customer = await tx.customer.findFirst({
        where: { id: data.id_client, organization_id: data.organization_id },
        select: { id: true, is_active: true },
      });
      if (!customer) {
        throw new APIError(404, {
          error: [{ field: 'id_client', message: 'Client introuvable ou accès refusé.' }],
        });
      }
      // Un client archivé ne reçoit plus d'expédition : la désactivation bloque l'écriture.
      if (!customer.is_active) {
        throw new APIError(409, {
          error: [
            { field: 'id_client', message: 'Ce client est archivé : aucune nouvelle expédition.' },
          ],
        });
      }

      // 0.b Préfixe entreprise GS1 de l'organisation (SSCC + URN LGTIN)
      const gs1Prefix = await resolveGs1Prefix(tx, data.organization_id);

      // 0.c Génération automatique de l'identifiant si demandé (Standard SSCC)
      let finalShipmentId = data.shipment_id;
      let ssccAutoGenerated = false;
      if (finalShipmentId === 'AUTO' || !finalShipmentId) {
        finalShipmentId = gs1Utils.generateSSCC(await nextSsccSerial(tx), gs1Prefix);
        ssccAutoGenerated = true;
      }

      // 1. Créer l'entête de l'expédition
      const shipment = await createShipmentOrRejectDuplicate(tx, {
        organization_id: data.organization_id,
        id_client: data.id_client,
        shipment_id: finalShipmentId,
        transporteur: data.transporteur,
        destination_adresse: data.destination_adresse,
        date_envoi: data.date_envoi,
        statut_livraison: 'EN_ROUTE',
        created_by: data.created_by,
      });

      // 2. Traiter chaque lot (Déduction de stock + Liaison)
      const shippedQuantities: Array<{ epcClass: string; quantity: number; uom: string }> = [];
      for (const item of data.items) {
        const batch = await tx.batch.findFirst({
          where: {
            id: item.id_lot,
            organization_id: data.organization_id,
          },
          include: { produit: { select: { code_gtin: true } } },
        });

        if (!batch) {
          throw new APIError(404, {
            error: [{ field: 'lots', message: `Lot ${item.id_lot} introuvable ou accès refusé.` }],
          });
        }

        // 3. Validation des règles métier (Qualité & Date)
        // Bloque l'expédition d'un lot en quarantaine (BLOQUE) ou sous rappel/alerte (ALERTE) :
        // un lot rappelé ne doit jamais pouvoir partir.
        if (isBatchBlocked(batch.statut)) {
          throw new APIError(400, {
            error: [
              {
                field: 'lots',
                message: `Le lot ${item.id_lot} est en statut ${batch.statut} et ne peut être expédié.`,
              },
            ],
          });
        }

        if (batch.date_peremption && batch.date_peremption < new Date()) {
          throw new APIError(400, {
            error: [{ field: 'lots', message: `Le lot ${item.id_lot} est périmé.` }],
          });
        }

        if (batch.quantite_actuelle.toNumber() < item.quantite) {
          throw new APIError(400, {
            error: [{ field: 'lots', message: `Stock insuffisant pour le lot ${item.id_lot}.` }],
          });
        }

        // 4. Déduire le stock — écriture CONDITIONNELLE (verrou optimiste). Le `where` rejoue les
        // gardes lues plus haut au moment de l'écriture : même version (aucune décision — rappel,
        // quarantaine, expédition concurrente — intercalée depuis la lecture) et statut non bloquant.
        // Si l'état a bougé, `count === 0` → 409 : on refuse plutôt que d'écraser la décision récente.
        const updated = await tx.batch.updateMany({
          where: {
            id: item.id_lot,
            organization_id: data.organization_id,
            version: batch.version,
            statut: { notIn: BLOCKING_BATCH_STATUSES as string[] },
          },
          data: {
            quantite_actuelle: { decrement: item.quantite },
            statut:
              batch.quantite_actuelle.toNumber() === item.quantite
                ? BATCH_STATUSES.SHIPPED
                : BATCH_STATUSES.IN_STOCK,
            version: { increment: 1 },
          },
        });

        if (updated.count === 0) {
          throw new APIError(409, {
            error: [
              {
                field: 'lots',
                message: `Le lot ${item.id_lot} a changé d'état pendant l'expédition (rappel, quarantaine ou expédition concurrente). Rechargez la fiche du lot avant de réessayer.`,
              },
            ],
          });
        }

        // Ce qui part chez le client quitte la palette : tout le lot, elle n'en déclare plus rien ;
        // une partie, elle n'en déclare pas plus que le reste.
        await reconcileLogisticUnitContent(tx, {
          batchId: item.id_lot,
          organizationId: data.organization_id,
          // Soustraction en Decimal, pas en `number` : `100.3 - 30.1` vaut 70.19999999999999 en
          // virgule flottante, et la palette afficherait ce nombre au scan pendant que le lot en
          // déclare 70.2. La transformation fait déjà la sienne en Decimal.
          remainingQuantity: batch.quantite_actuelle.minus(item.quantite).toNumber(),
        });

        // 5. Créer la liaison
        await tx.liaison_Shipment.create({
          data: {
            id_expedition: shipment.id,
            id_lot: item.id_lot,
            quantite_expediee: item.quantite,
            unite: batch.unite_code,
          },
        });

        // 6. Enregistrer le mouvement (Audit-Trail)
        await tx.batch_Mouvement.create({
          data: {
            id_lot: item.id_lot,
            type_action: MOVEMENT_TYPES.SHIPMENT,
            quantite: item.quantite,
            unite: batch.unite_code,
            id_expedition: shipment.id,
            id_user: data.created_by,
          },
        });

        shippedQuantities.push({
          epcClass: gs1Utils.buildLgtinUrn(gs1Prefix, batch.produit.code_gtin, batch.lot_number),
          quantity: item.quantite,
          uom: batch.unite_code,
        });
      }

      // 7. Événement EPCIS ObjectEvent : sortie des lots de la chaîne lors de l'expédition.
      // Lots identifiés au niveau classe (URN LGTIN) dans quantityList.
      await tx.ePCIS_Event.create({
        data: {
          organization_id: data.organization_id,
          event_time: new Date(),
          event_type: EPCIS_EVENT_TYPE.object,
          related_entity: EPCIS_RELATED_ENTITY.shipment,
          related_id: shipment.id,
          payload: {
            quantityList: shippedQuantities,
            action: EPCIS_ACTION.observe,
            bizStep: EPCIS_BIZSTEP.shipping,
            disposition: EPCIS_DISPOSITION.inTransit,
            destinationParty: data.id_client,
            sscc: finalShipmentId,
          },
        },
      });

      // 8. Événement EPCIS AggregationEvent : le contenant (SSCC) agrège les lots expédiés.
      // L'URN SSCC n'a de sens que pour un SSCC que NOUS avons généré avec ce préfixe ;
      // un identifiant fourni par l'appelant (même 18 chiffres) est conservé tel quel.
      const parentId = ssccAutoGenerated
        ? gs1Utils.buildSsccUrn(gs1Prefix, finalShipmentId)
        : finalShipmentId;

      await tx.ePCIS_Event.create({
        data: {
          organization_id: data.organization_id,
          event_time: new Date(),
          event_type: EPCIS_EVENT_TYPE.aggregation,
          related_entity: EPCIS_RELATED_ENTITY.shipment,
          related_id: shipment.id,
          payload: {
            parentID: parentId,
            childQuantityList: shippedQuantities,
            action: EPCIS_ACTION.add,
            bizStep: EPCIS_BIZSTEP.shipping,
          },
        },
      });

      // 9. Audit WORM — l'expédition est le moment où la marchandise quitte l'usine. Sans ce maillon,
      // « qui a expédié ce lot, quand, vers qui » ne reposait que sur Batch_Mouvement (mutable, non
      // chaîné) : la preuve d'intégrité s'arrêtait à la porte du camion. Scellé DANS la transaction.
      await auditService.logAction(
        {
          organizationId: data.organization_id,
          userId: data.created_by,
          action: 'CREATE_SHIPMENT',
          entity: 'Shipment',
          entityId: shipment.id,
          newValue: {
            shipment_id: finalShipmentId,
            id_client: data.id_client,
            transporteur: data.transporteur,
            date_envoi: data.date_envoi,
            lots: data.items.map((i) => ({ id_lot: i.id_lot, quantite: i.quantite })),
          },
        },
        tx
      );

      return shipment;
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
  },
};
