import { prisma } from '../../../../shared/configs/prismaClient.config';
import { APIError } from '../../../../shared/utils/errorHandler/APIError';
import { gs1Utils } from '../../../../shared/utils/gs1/gs1.utils';
import { resolveGs1Prefix } from '../../../../shared/utils/gs1/gs1Prefix';
import {
  EPCIS_ACTION,
  EPCIS_BIZSTEP,
  EPCIS_DISPOSITION,
  EPCIS_EVENT_TYPE,
  EPCIS_RELATED_ENTITY,
} from '../../../../shared/constants/epcis.constants';
import {
  BATCH_STATUSES,
  MOVEMENT_TYPES,
  isBatchBlocked,
} from '../../constants/logistics.constants';

/**
 * Service pour la gestion des Expéditions (Shipments)
 */
export const shipmentService = {
  /**
   * Créer une expédition et déduire les stocks des lots associés.
   */
  async createShipment(data: {
    organization_id: string;
    id_client: string;
    shipment_id: string;
    transporteur: string;
    destination_adresse?: string;
    date_envoi: Date;
    created_by: string;
    items: Array<{ id_lot: string; quantite: number }>;
  }) {
    return await prisma.$transaction(async (tx) => {
      // 0.a Le client destinataire doit appartenir à l'organisation (anti-référence cross-tenant).
      // Symétrique au contrôle du fournisseur à la réception : sans cette garde, un id_client
      // d'une autre org serait accepté (et notifié lors d'un rappel).
      const customer = await tx.customer.findFirst({
        where: { id: data.id_client, organization_id: data.organization_id },
        select: { id: true, is_active: true },
      });
      if (!customer) {
        throw new APIError(404, {
          error: [{ field: 'id_client', message: 'Client introuvable ou accès refusé.' }],
        });
      }
      // Un client archivé ne reçoit plus d'expédition : la désactivation bloque l'écriture.
      if (!customer.is_active) {
        throw new APIError(409, {
          error: [
            { field: 'id_client', message: 'Ce client est archivé : aucune nouvelle expédition.' },
          ],
        });
      }

      // 0.b Préfixe entreprise GS1 de l'organisation (SSCC + URN LGTIN)
      const gs1Prefix = await resolveGs1Prefix(tx, data.organization_id);

      // 0.c Génération automatique de l'identifiant si demandé (Standard SSCC)
      let finalShipmentId = data.shipment_id;
      let ssccAutoGenerated = false;
      if (finalShipmentId === 'AUTO' || !finalShipmentId) {
        const count = await tx.shipment.count({ where: { organization_id: data.organization_id } });
        finalShipmentId = gs1Utils.generateSSCC(count + 1, gs1Prefix);
        ssccAutoGenerated = true;
      }

      // 1. Créer l'entête de l'expédition
      const shipment = await tx.shipment.create({
        data: {
          organization_id: data.organization_id,
          id_client: data.id_client,
          shipment_id: finalShipmentId,
          transporteur: data.transporteur,
          destination_adresse: data.destination_adresse,
          date_envoi: data.date_envoi,
          statut_livraison: 'EN_ROUTE',
          created_by: data.created_by,
        },
      });

      // 2. Traiter chaque lot (Déduction de stock + Liaison)
      const shippedQuantities: Array<{ epcClass: string; quantity: number; uom: string }> = [];
      for (const item of data.items) {
        const batch = await tx.batch.findFirst({
          where: {
            id: item.id_lot,
            organization_id: data.organization_id,
          },
          include: { produit: { select: { code_gtin: true } } },
        });

        if (!batch) {
          throw new APIError(404, {
            error: [{ field: 'lots', message: `Lot ${item.id_lot} introuvable ou accès refusé.` }],
          });
        }

        // 3. Validation des règles métier (Qualité & Date)
        // Bloque l'expédition d'un lot en quarantaine (BLOQUE) ou sous rappel/alerte (ALERTE) :
        // un lot rappelé ne doit jamais pouvoir partir.
        if (isBatchBlocked(batch.statut)) {
          throw new APIError(400, {
            error: [
              {
                field: 'lots',
                message: `Le lot ${item.id_lot} est en statut ${batch.statut} et ne peut être expédié.`,
              },
            ],
          });
        }

        if (batch.date_peremption && batch.date_peremption < new Date()) {
          throw new APIError(400, {
            error: [{ field: 'lots', message: `Le lot ${item.id_lot} est périmé.` }],
          });
        }

        if (batch.quantite_actuelle.toNumber() < item.quantite) {
          throw new APIError(400, {
            error: [{ field: 'lots', message: `Stock insuffisant pour le lot ${item.id_lot}.` }],
          });
        }

        // 4. Déduire le stock
        await tx.batch.update({
          where: { id: item.id_lot },
          data: {
            quantite_actuelle: { decrement: item.quantite },
            statut:
              batch.quantite_actuelle.toNumber() === item.quantite
                ? BATCH_STATUSES.SHIPPED
                : BATCH_STATUSES.IN_STOCK,
          },
        });

        // 5. Créer la liaison
        await tx.liaison_Shipment.create({
          data: {
            id_expedition: shipment.id,
            id_lot: item.id_lot,
            quantite_expediee: item.quantite,
            unite: batch.unite_code,
          },
        });

        // 6. Enregistrer le mouvement (Audit-Trail)
        await tx.batch_Mouvement.create({
          data: {
            id_lot: item.id_lot,
            type_action: MOVEMENT_TYPES.SHIPMENT,
            quantite: item.quantite,
            unite: batch.unite_code,
            id_expedition: shipment.id,
            id_user: data.created_by,
          },
        });

        shippedQuantities.push({
          epcClass: gs1Utils.buildLgtinUrn(gs1Prefix, batch.produit.code_gtin, batch.lot_number),
          quantity: item.quantite,
          uom: batch.unite_code,
        });
      }

      // 7. Événement EPCIS ObjectEvent : sortie des lots de la chaîne lors de l'expédition.
      // Lots identifiés au niveau classe (URN LGTIN) dans quantityList.
      await tx.ePCIS_Event.create({
        data: {
          organization_id: data.organization_id,
          event_time: new Date(),
          event_type: EPCIS_EVENT_TYPE.object,
          related_entity: EPCIS_RELATED_ENTITY.shipment,
          related_id: shipment.id,
          payload: {
            quantityList: shippedQuantities,
            action: EPCIS_ACTION.observe,
            bizStep: EPCIS_BIZSTEP.shipping,
            disposition: EPCIS_DISPOSITION.inTransit,
            destinationParty: data.id_client,
            sscc: finalShipmentId,
          },
        },
      });

      // 8. Événement EPCIS AggregationEvent : le contenant (SSCC) agrège les lots expédiés.
      // L'URN SSCC n'a de sens que pour un SSCC que NOUS avons généré avec ce préfixe ;
      // un identifiant fourni par l'appelant (même 18 chiffres) est conservé tel quel.
      const parentId = ssccAutoGenerated
        ? gs1Utils.buildSsccUrn(gs1Prefix, finalShipmentId)
        : finalShipmentId;

      await tx.ePCIS_Event.create({
        data: {
          organization_id: data.organization_id,
          event_time: new Date(),
          event_type: EPCIS_EVENT_TYPE.aggregation,
          related_entity: EPCIS_RELATED_ENTITY.shipment,
          related_id: shipment.id,
          payload: {
            parentID: parentId,
            childQuantityList: shippedQuantities,
            action: EPCIS_ACTION.add,
            bizStep: EPCIS_BIZSTEP.shipping,
          },
        },
      });

      return shipment;
    });
  },
};
